apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: demo1
  labels:
    strimzi.io/cluster: <your-project>
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: demo2
  labels:
    strimzi.io/cluster: <your-project>
spec:
  partitions: 4
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: demo3
  labels:
    strimzi.io/cluster: <your-project>
spec:
  partitions: 4
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
